version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests

artifacts:
  files:
    - target/gestion-pedidos-0.0.1-SNAPSHOT.jar
    - Procfile
