version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests
      - cp target/gestion-pedidos-0.0.1-SNAPSHOT.jar gestion-pedidos-0.0.1-SNAPSHOT.jar

artifacts:
  files:
    - gestion-pedidos-0.0.1-SNAPSHOT.jar
    - Procfile
  discard-paths: yes
